"""
rebuild_index.py — Wipe and Rebuild Vector Indices for Multilingual Models
─────────────────────────────────────────────────────────────────────────
Run from backend directory:
  python rebuild_index.py [--user USER_ID] [--all]

WHY THIS IS NEEDED:
  When switching EMBEDDING_MODEL in .env (e.g. from English-only
  'sentence-transformers/all-MiniLM-L6-v2' to multilingual
  'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'), existing
  FAISS indices created with the old model become incompatible. Vector
  embeddings generated by different models cannot be compared.

WHAT THIS SCRIPT DOES:
  1. Deletes vectorstore/{user_id}/faiss_index/ directory.
  2. Clears in-memory retriever cache (invalidate_user_cache).
  3. Resets document store metadata for the affected user(s).
  4. Provides instructions for re-uploading documents.
"""

import os
import sys
import shutil
import argparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.retriever import invalidate_user_cache
from src.document_store import get_all_documents, remove_document
from src.config import EMBEDDING_MODEL


def wipe_user_index(user_id: str):
    """Wipe vector index and stored documents for a specific user_id."""
    print(f"[REBUILD] Wiping index for user '{user_id}'...")

    # 1. Clear in-memory retriever cache
    invalidate_user_cache(user_id)

    # 2. Delete FAISS directory on disk
    index_dir = os.path.join("vectorstore", user_id)
    if os.path.exists(index_dir):
        shutil.rmtree(index_dir)
        print(f"[REBUILD] Removed directory: {index_dir}")
    else:
        print(f"[REBUILD] No vector directory found for user '{user_id}'")

    # 3. Clear document store registry entries
    docs = get_all_documents(user_id)
    for doc in docs:
        remove_document(user_id, doc["filename"])
    print(f"[REBUILD] Cleared {len(docs)} document record(s) from registry.")


def main():
    parser = argparse.ArgumentParser(description="Wipe and reset vector indices when changing EMBEDDING_MODEL.")
    parser.add_argument("--user", type=str, help="Specific user_id to reset")
    parser.add_argument("--all", action="store_true", help="Reset all user indices")
    args = parser.parse_args()

    print(f"\n{'='*70}")
    print(f"  INDEX REBUILD & RESET TOOL")
    print(f"  Active EMBEDDING_MODEL: {EMBEDDING_MODEL}")
    print(f"{'='*70}\n")

    vs_dir = "vectorstore"
    if not os.path.exists(vs_dir):
        print("[REBUILD] No vectorstore directory exists.")
        return

    if args.user:
        wipe_user_index(args.user)
    elif args.all:
        for entry in os.listdir(vs_dir):
            if os.path.isdir(os.path.join(vs_dir, entry)):
                wipe_user_index(entry)
    else:
        print("Please specify --user USER_ID or --all to wipe vector indices.")
        print("Example:\n  python rebuild_index.py --all\n")
        return

    print("\n✅ Reset complete. You can now upload/re-ingest documents using the current EMBEDDING_MODEL.")


if __name__ == "__main__":
    main()
